/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardLayoutRouteRouteImport } from './routes/_dashboardLayout/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardLayoutactiveOrdersActiveOrdersRouteImport } from './routes/_dashboardLayout/(active-orders)/active-orders'
import { Route as DashboardLayoutdashboardDashboardRouteImport } from './routes/_dashboardLayout/(dashboard)/dashboard'
import { Route as DashboardLayoutmessagesMessagesRouteImport } from './routes/_dashboardLayout/(messages)/messages'
import { Route as DashboardLayoutmyRequestsMyRequestsRouteImport } from './routes/_dashboardLayout/(my-requests)/my-requests'
import { Route as DashboardLayoutmyRequestsUploadRouteImport } from './routes/_dashboardLayout/(my-requests)/upload'
import { Route as DashboardLayoutpaymentHistoryPaymentHistoryRouteImport } from './routes/_dashboardLayout/(payment-history)/payment-history'
import { Route as DashboardLayoutprofileProfileRouteImport } from './routes/_dashboardLayout/(profile)/profile'
import { Route as DashboardLayoutmyRequestsMyRequestsRequestIdRouteImport } from './routes/_dashboardLayout/(my-requests)/my-requests_.$requestId'
import { Route as DashboardLayoutactiveOrdersActiveOrdersOrderIdOrderDetailsRouteImport } from './routes/_dashboardLayout/(active-orders)/active-orders_.$orderId.order-details'
import { Route as DashboardLayoutactiveOrdersActiveOrdersOrderIdReviewRouteImport } from './routes/_dashboardLayout/(active-orders)/active-orders_.$orderId.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRouteRoute = DashboardLayoutRouteRouteImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutactiveOrdersActiveOrdersRoute =
  DashboardLayoutactiveOrdersActiveOrdersRouteImport.update({
    id: '/(active-orders)/active-orders',
    path: '/active-orders',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutdashboardDashboardRoute =
  DashboardLayoutdashboardDashboardRouteImport.update({
    id: '/(dashboard)/dashboard',
    path: '/dashboard',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutmessagesMessagesRoute =
  DashboardLayoutmessagesMessagesRouteImport.update({
    id: '/(messages)/messages',
    path: '/messages',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutmyRequestsMyRequestsRoute =
  DashboardLayoutmyRequestsMyRequestsRouteImport.update({
    id: '/(my-requests)/my-requests',
    path: '/my-requests',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutmyRequestsUploadRoute =
  DashboardLayoutmyRequestsUploadRouteImport.update({
    id: '/(my-requests)/upload',
    path: '/upload',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutpaymentHistoryPaymentHistoryRoute =
  DashboardLayoutpaymentHistoryPaymentHistoryRouteImport.update({
    id: '/(payment-history)/payment-history',
    path: '/payment-history',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutprofileProfileRoute =
  DashboardLayoutprofileProfileRouteImport.update({
    id: '/(profile)/profile',
    path: '/profile',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutmyRequestsMyRequestsRequestIdRoute =
  DashboardLayoutmyRequestsMyRequestsRequestIdRouteImport.update({
    id: '/(my-requests)/my-requests_/$requestId',
    path: '/my-requests/$requestId',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutactiveOrdersActiveOrdersOrderIdOrderDetailsRoute =
  DashboardLayoutactiveOrdersActiveOrdersOrderIdOrderDetailsRouteImport.update({
    id: '/(active-orders)/active-orders_/$orderId/order-details',
    path: '/active-orders/$orderId/order-details',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutactiveOrdersActiveOrdersOrderIdReviewRoute =
  DashboardLayoutactiveOrdersActiveOrdersOrderIdReviewRouteImport.update({
    id: '/(active-orders)/active-orders_/$orderId/review',
    path: '/active-orders/$orderId/review',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/active-orders': typeof DashboardLayoutactiveOrdersActiveOrdersRoute
  '/dashboard': typeof DashboardLayoutdashboardDashboardRoute
  '/messages': typeof DashboardLayoutmessagesMessagesRoute
  '/my-requests': typeof DashboardLayoutmyRequestsMyRequestsRoute
  '/upload': typeof DashboardLayoutmyRequestsUploadRoute
  '/payment-history': typeof DashboardLayoutpaymentHistoryPaymentHistoryRoute
  '/profile': typeof DashboardLayoutprofileProfileRoute
  '/my-requests/$requestId': typeof DashboardLayoutmyRequestsMyRequestsRequestIdRoute
  '/active-orders/$orderId/order-details': typeof DashboardLayoutactiveOrdersActiveOrdersOrderIdOrderDetailsRoute
  '/active-orders/$orderId/review': typeof DashboardLayoutactiveOrdersActiveOrdersOrderIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/active-orders': typeof DashboardLayoutactiveOrdersActiveOrdersRoute
  '/dashboard': typeof DashboardLayoutdashboardDashboardRoute
  '/messages': typeof DashboardLayoutmessagesMessagesRoute
  '/my-requests': typeof DashboardLayoutmyRequestsMyRequestsRoute
  '/upload': typeof DashboardLayoutmyRequestsUploadRoute
  '/payment-history': typeof DashboardLayoutpaymentHistoryPaymentHistoryRoute
  '/profile': typeof DashboardLayoutprofileProfileRoute
  '/my-requests/$requestId': typeof DashboardLayoutmyRequestsMyRequestsRequestIdRoute
  '/active-orders/$orderId/order-details': typeof DashboardLayoutactiveOrdersActiveOrdersOrderIdOrderDetailsRoute
  '/active-orders/$orderId/review': typeof DashboardLayoutactiveOrdersActiveOrdersOrderIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboardLayout': typeof DashboardLayoutRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboardLayout/(active-orders)/active-orders': typeof DashboardLayoutactiveOrdersActiveOrdersRoute
  '/_dashboardLayout/(dashboard)/dashboard': typeof DashboardLayoutdashboardDashboardRoute
  '/_dashboardLayout/(messages)/messages': typeof DashboardLayoutmessagesMessagesRoute
  '/_dashboardLayout/(my-requests)/my-requests': typeof DashboardLayoutmyRequestsMyRequestsRoute
  '/_dashboardLayout/(my-requests)/upload': typeof DashboardLayoutmyRequestsUploadRoute
  '/_dashboardLayout/(payment-history)/payment-history': typeof DashboardLayoutpaymentHistoryPaymentHistoryRoute
  '/_dashboardLayout/(profile)/profile': typeof DashboardLayoutprofileProfileRoute
  '/_dashboardLayout/(my-requests)/my-requests_/$requestId': typeof DashboardLayoutmyRequestsMyRequestsRequestIdRoute
  '/_dashboardLayout/(active-orders)/active-orders_/$orderId/order-details': typeof DashboardLayoutactiveOrdersActiveOrdersOrderIdOrderDetailsRoute
  '/_dashboardLayout/(active-orders)/active-orders_/$orderId/review': typeof DashboardLayoutactiveOrdersActiveOrdersOrderIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/active-orders'
    | '/dashboard'
    | '/messages'
    | '/my-requests'
    | '/upload'
    | '/payment-history'
    | '/profile'
    | '/my-requests/$requestId'
    | '/active-orders/$orderId/order-details'
    | '/active-orders/$orderId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/active-orders'
    | '/dashboard'
    | '/messages'
    | '/my-requests'
    | '/upload'
    | '/payment-history'
    | '/profile'
    | '/my-requests/$requestId'
    | '/active-orders/$orderId/order-details'
    | '/active-orders/$orderId/review'
  id:
    | '__root__'
    | '/'
    | '/_dashboardLayout'
    | '/login'
    | '/_dashboardLayout/(active-orders)/active-orders'
    | '/_dashboardLayout/(dashboard)/dashboard'
    | '/_dashboardLayout/(messages)/messages'
    | '/_dashboardLayout/(my-requests)/my-requests'
    | '/_dashboardLayout/(my-requests)/upload'
    | '/_dashboardLayout/(payment-history)/payment-history'
    | '/_dashboardLayout/(profile)/profile'
    | '/_dashboardLayout/(my-requests)/my-requests_/$requestId'
    | '/_dashboardLayout/(active-orders)/active-orders_/$orderId/order-details'
    | '/_dashboardLayout/(active-orders)/active-orders_/$orderId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRouteRoute: typeof DashboardLayoutRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout': {
      id: '/_dashboardLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout/(active-orders)/active-orders': {
      id: '/_dashboardLayout/(active-orders)/active-orders'
      path: '/active-orders'
      fullPath: '/active-orders'
      preLoaderRoute: typeof DashboardLayoutactiveOrdersActiveOrdersRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/(dashboard)/dashboard': {
      id: '/_dashboardLayout/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutdashboardDashboardRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/(messages)/messages': {
      id: '/_dashboardLayout/(messages)/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof DashboardLayoutmessagesMessagesRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/(my-requests)/my-requests': {
      id: '/_dashboardLayout/(my-requests)/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof DashboardLayoutmyRequestsMyRequestsRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/(my-requests)/upload': {
      id: '/_dashboardLayout/(my-requests)/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof DashboardLayoutmyRequestsUploadRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/(payment-history)/payment-history': {
      id: '/_dashboardLayout/(payment-history)/payment-history'
      path: '/payment-history'
      fullPath: '/payment-history'
      preLoaderRoute: typeof DashboardLayoutpaymentHistoryPaymentHistoryRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/(profile)/profile': {
      id: '/_dashboardLayout/(profile)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardLayoutprofileProfileRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/(my-requests)/my-requests_/$requestId': {
      id: '/_dashboardLayout/(my-requests)/my-requests_/$requestId'
      path: '/my-requests/$requestId'
      fullPath: '/my-requests/$requestId'
      preLoaderRoute: typeof DashboardLayoutmyRequestsMyRequestsRequestIdRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/(active-orders)/active-orders_/$orderId/order-details': {
      id: '/_dashboardLayout/(active-orders)/active-orders_/$orderId/order-details'
      path: '/active-orders/$orderId/order-details'
      fullPath: '/active-orders/$orderId/order-details'
      preLoaderRoute: typeof DashboardLayoutactiveOrdersActiveOrdersOrderIdOrderDetailsRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/(active-orders)/active-orders_/$orderId/review': {
      id: '/_dashboardLayout/(active-orders)/active-orders_/$orderId/review'
      path: '/active-orders/$orderId/review'
      fullPath: '/active-orders/$orderId/review'
      preLoaderRoute: typeof DashboardLayoutactiveOrdersActiveOrdersOrderIdReviewRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
  }
}

interface DashboardLayoutRouteRouteChildren {
  DashboardLayoutactiveOrdersActiveOrdersRoute: typeof DashboardLayoutactiveOrdersActiveOrdersRoute
  DashboardLayoutdashboardDashboardRoute: typeof DashboardLayoutdashboardDashboardRoute
  DashboardLayoutmessagesMessagesRoute: typeof DashboardLayoutmessagesMessagesRoute
  DashboardLayoutmyRequestsMyRequestsRoute: typeof DashboardLayoutmyRequestsMyRequestsRoute
  DashboardLayoutmyRequestsUploadRoute: typeof DashboardLayoutmyRequestsUploadRoute
  DashboardLayoutpaymentHistoryPaymentHistoryRoute: typeof DashboardLayoutpaymentHistoryPaymentHistoryRoute
  DashboardLayoutprofileProfileRoute: typeof DashboardLayoutprofileProfileRoute
  DashboardLayoutmyRequestsMyRequestsRequestIdRoute: typeof DashboardLayoutmyRequestsMyRequestsRequestIdRoute
  DashboardLayoutactiveOrdersActiveOrdersOrderIdOrderDetailsRoute: typeof DashboardLayoutactiveOrdersActiveOrdersOrderIdOrderDetailsRoute
  DashboardLayoutactiveOrdersActiveOrdersOrderIdReviewRoute: typeof DashboardLayoutactiveOrdersActiveOrdersOrderIdReviewRoute
}

const DashboardLayoutRouteRouteChildren: DashboardLayoutRouteRouteChildren = {
  DashboardLayoutactiveOrdersActiveOrdersRoute:
    DashboardLayoutactiveOrdersActiveOrdersRoute,
  DashboardLayoutdashboardDashboardRoute:
    DashboardLayoutdashboardDashboardRoute,
  DashboardLayoutmessagesMessagesRoute: DashboardLayoutmessagesMessagesRoute,
  DashboardLayoutmyRequestsMyRequestsRoute:
    DashboardLayoutmyRequestsMyRequestsRoute,
  DashboardLayoutmyRequestsUploadRoute: DashboardLayoutmyRequestsUploadRoute,
  DashboardLayoutpaymentHistoryPaymentHistoryRoute:
    DashboardLayoutpaymentHistoryPaymentHistoryRoute,
  DashboardLayoutprofileProfileRoute: DashboardLayoutprofileProfileRoute,
  DashboardLayoutmyRequestsMyRequestsRequestIdRoute:
    DashboardLayoutmyRequestsMyRequestsRequestIdRoute,
  DashboardLayoutactiveOrdersActiveOrdersOrderIdOrderDetailsRoute:
    DashboardLayoutactiveOrdersActiveOrdersOrderIdOrderDetailsRoute,
  DashboardLayoutactiveOrdersActiveOrdersOrderIdReviewRoute:
    DashboardLayoutactiveOrdersActiveOrdersOrderIdReviewRoute,
}

const DashboardLayoutRouteRouteWithChildren =
  DashboardLayoutRouteRoute._addFileChildren(DashboardLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRouteRoute: DashboardLayoutRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
