/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardLayoutRouteRouteImport } from './routes/_dashboardLayout/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardLayoutdashboardDashboardRouteImport } from './routes/_dashboardLayout/(dashboard)/dashboard'
import { Route as DashboardLayoutmyRequestsMyRequestsRouteImport } from './routes/_dashboardLayout/(my-requests)/my-requests'
import { Route as DashboardLayoutmyRequestsUploadRouteImport } from './routes/_dashboardLayout/(my-requests)/upload'
import { Route as DashboardLayoutmyRequestsMyRequestsRequestIdRouteImport } from './routes/_dashboardLayout/(my-requests)/my-requests_.$requestId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRouteRoute = DashboardLayoutRouteRouteImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutdashboardDashboardRoute =
  DashboardLayoutdashboardDashboardRouteImport.update({
    id: '/(dashboard)/dashboard',
    path: '/dashboard',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutmyRequestsMyRequestsRoute =
  DashboardLayoutmyRequestsMyRequestsRouteImport.update({
    id: '/(my-requests)/my-requests',
    path: '/my-requests',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutmyRequestsUploadRoute =
  DashboardLayoutmyRequestsUploadRouteImport.update({
    id: '/(my-requests)/upload',
    path: '/upload',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutmyRequestsMyRequestsRequestIdRoute =
  DashboardLayoutmyRequestsMyRequestsRequestIdRouteImport.update({
    id: '/(my-requests)/my-requests_/$requestId',
    path: '/my-requests/$requestId',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardLayoutdashboardDashboardRoute
  '/my-requests': typeof DashboardLayoutmyRequestsMyRequestsRoute
  '/upload': typeof DashboardLayoutmyRequestsUploadRoute
  '/my-requests/$requestId': typeof DashboardLayoutmyRequestsMyRequestsRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardLayoutdashboardDashboardRoute
  '/my-requests': typeof DashboardLayoutmyRequestsMyRequestsRoute
  '/upload': typeof DashboardLayoutmyRequestsUploadRoute
  '/my-requests/$requestId': typeof DashboardLayoutmyRequestsMyRequestsRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboardLayout': typeof DashboardLayoutRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboardLayout/(dashboard)/dashboard': typeof DashboardLayoutdashboardDashboardRoute
  '/_dashboardLayout/(my-requests)/my-requests': typeof DashboardLayoutmyRequestsMyRequestsRoute
  '/_dashboardLayout/(my-requests)/upload': typeof DashboardLayoutmyRequestsUploadRoute
  '/_dashboardLayout/(my-requests)/my-requests_/$requestId': typeof DashboardLayoutmyRequestsMyRequestsRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/my-requests'
    | '/upload'
    | '/my-requests/$requestId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/my-requests'
    | '/upload'
    | '/my-requests/$requestId'
  id:
    | '__root__'
    | '/'
    | '/_dashboardLayout'
    | '/login'
    | '/_dashboardLayout/(dashboard)/dashboard'
    | '/_dashboardLayout/(my-requests)/my-requests'
    | '/_dashboardLayout/(my-requests)/upload'
    | '/_dashboardLayout/(my-requests)/my-requests_/$requestId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRouteRoute: typeof DashboardLayoutRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout': {
      id: '/_dashboardLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout/(dashboard)/dashboard': {
      id: '/_dashboardLayout/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutdashboardDashboardRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/(my-requests)/my-requests': {
      id: '/_dashboardLayout/(my-requests)/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof DashboardLayoutmyRequestsMyRequestsRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/(my-requests)/upload': {
      id: '/_dashboardLayout/(my-requests)/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof DashboardLayoutmyRequestsUploadRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/(my-requests)/my-requests_/$requestId': {
      id: '/_dashboardLayout/(my-requests)/my-requests_/$requestId'
      path: '/my-requests/$requestId'
      fullPath: '/my-requests/$requestId'
      preLoaderRoute: typeof DashboardLayoutmyRequestsMyRequestsRequestIdRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
  }
}

interface DashboardLayoutRouteRouteChildren {
  DashboardLayoutdashboardDashboardRoute: typeof DashboardLayoutdashboardDashboardRoute
  DashboardLayoutmyRequestsMyRequestsRoute: typeof DashboardLayoutmyRequestsMyRequestsRoute
  DashboardLayoutmyRequestsUploadRoute: typeof DashboardLayoutmyRequestsUploadRoute
  DashboardLayoutmyRequestsMyRequestsRequestIdRoute: typeof DashboardLayoutmyRequestsMyRequestsRequestIdRoute
}

const DashboardLayoutRouteRouteChildren: DashboardLayoutRouteRouteChildren = {
  DashboardLayoutdashboardDashboardRoute:
    DashboardLayoutdashboardDashboardRoute,
  DashboardLayoutmyRequestsMyRequestsRoute:
    DashboardLayoutmyRequestsMyRequestsRoute,
  DashboardLayoutmyRequestsUploadRoute: DashboardLayoutmyRequestsUploadRoute,
  DashboardLayoutmyRequestsMyRequestsRequestIdRoute:
    DashboardLayoutmyRequestsMyRequestsRequestIdRoute,
}

const DashboardLayoutRouteRouteWithChildren =
  DashboardLayoutRouteRoute._addFileChildren(DashboardLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRouteRoute: DashboardLayoutRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
